version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql-db-ddsi-p3
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ddsip3
    ports:
      - "3000:3306"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-interface-ddsi-p3
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db

